# NOTE: update this with your service name
service: blob-images-api-invites

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: eu-central-1
  tags:
    APP: clubalmanac

  environment:
    photoTable: ${file(./serverlessDomainConfig.js):photoTable.${self:provider.stage}}
    coverIndex: cover-idx
    photoIndex: SK-PK-idx
    emailIndex: email-idx
    cognitoIndex: cog-idx
    dateIndex: date-idx
    photoBucket: blob-images
    frontend: ${file(./serverlessDomainConfig.js):frontend.${self:provider.stage}}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeStream
        - dynamodb:ListStreams
      Resource: "arn:aws:dynamodb:eu-central-1:*:*"
    - Effect: Allow
      Action:
        - ses:SendEmail
        - ses:SendRawEmail
        - ses:SendTemplatedEmail
        - ses:SendBulkTemplatedEmail
      Resource: "arn:aws:ses:eu-central-1:*:*"
    - Effect: Allow
      Action:
        - s3:getObject
      Resource: "arn:aws:s3:::*"

functions:
  publicGetInvite:
    handler: handlersInvite/publicGetInvite.main
    events:
      - http:
          path: /{id}
          method: get
          cors: true
          authorizer: aws_iam
  acceptInvite:
    handler: handlersInvite/acceptInvite.main
    events:
      - http:
          path: /{id}
          method: post
          cors: true
          authorizer: aws_iam
  declineInvite:
    handler: handlersInvite/acceptInvite.main
    events:
      - http:
          path: /{id}
          method: delete
          cors: true
          authorizer: aws_iam

custom:
  customDomain:
    domainName: ${file(./serverlessDomainConfig.js):domain.${self:provider.stage}}
    basePath: 'invites'
    stage: ${self:provider.stage}
    createRoute53Record: false

resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}